package com.example.a2madrid.presentation.theme

import androidx.compose.ui.graphics.Color

// --- Light scheme (Madrid crimson + gold accents) ---
val PrimaryLight = Color(0xFFBC1A2B)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFFDAD7)
val OnPrimaryContainerLight = Color(0xFF410007)
val SecondaryLight = Color(0xFF775653)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFFFDAD7)
val OnSecondaryContainerLight = Color(0xFF2C1513)
val TertiaryLight = Color(0xFF785A00)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFDF9A)
val OnTertiaryContainerLight = Color(0xFF261A00)
val BackgroundLight = Color(0xFFFFF8F7)
val OnBackgroundLight = Color(0xFF231919)
val SurfaceLight = Color(0xFFFFF8F7)
val OnSurfaceLight = Color(0xFF231919)
val SurfaceVariantLight = Color(0xFFF5DDDA)
val OnSurfaceVariantLight = Color(0xFF534341)
val OutlineLight = Color(0xFF857371)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

// --- Dark scheme ---
val PrimaryDark = Color(0xFFFFB3AE)
val OnPrimaryDark = Color(0xFF680012)
val PrimaryContainerDark = Color(0xFF930020)
val OnPrimaryContainerDark = Color(0xFFFFDAD7)
val SecondaryDark = Color(0xFFE7BDB8)
val OnSecondaryDark = Color(0xFF442927)
val SecondaryContainerDark = Color(0xFF5D3F3C)
val OnSecondaryContainerDark = Color(0xFFFFDAD7)
val TertiaryDark = Color(0xFFEDC04D)
val OnTertiaryDark = Color(0xFF3F2E00)
val TertiaryContainerDark = Color(0xFF5B4300)
val OnTertiaryContainerDark = Color(0xFFFFDF9A)
val BackgroundDark = Color(0xFF1A1110)
val OnBackgroundDark = Color(0xFFF0DEDC)
val SurfaceDark = Color(0xFF1A1110)
val OnSurfaceDark = Color(0xFFF0DEDC)
val SurfaceVariantDark = Color(0xFF534341)
val OnSurfaceVariantDark = Color(0xFFD8C2BF)
val OutlineDark = Color(0xFFA08C8A)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)